apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-service-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jbrcoleman/python-service-argocd'
    targetRevision: HEAD
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true