apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service
  namespace: web-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-service
  template:
    metadata:
      labels:
        app: web-service
    spec:
      containers:
      - name: web-service
        image: jbrcoleman/gopher-web-service:1.0.0
        ports:
        - containerPort: 80