apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-services
  namespace: web-service
subjects:
- kind: ServiceAccount
  name: default
  namespace: python-service
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io